services:
  my-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - node_modules:/app/node_modules
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - traefik.http.routers.my-portfolio.rule=Host(`adrien-bony.fr`)
      - "traefik.http.routers.my-portfolio.tls.certresolver=myresolver"

volumes:
  node_modules:

networks:
  proxy:
    external: true
