services:
  my-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "82:80"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: unless-stopped
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - proxy

volumes:
  node_modules:

networks:
  proxy:
    name: proxy_network
    external: true