version: '3.8'

services:
  my-portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-portfolio
    ports:
      - "82:80"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    restart: unless-stopped
    command: ["nginx", "-g", "daemon off;"]

volumes:
  node_modules: